---
# Uninstall MapR collectd
- name: Stop Collectd
  shell: maprcli node services -name collectd -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-collectd
  package: name=mapr-collectd state=absent
