---
# Uninstall Sqoop2 Server
- name: Stop Sqoop2 Server
  shell: maprcli node services -name sqoop2 -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-sqoop2-server
  package: name=mapr-sqoop2-server state=absent
