---
# Uninstall Oozie and MySQL
- name: Stop Oozie
  shell: maprcli node services -name oozie -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-oozie
  package: name=mapr-oozie state=absent


