---
# Restart  Warden
- name: Restart MapR Warden
  service: name=mapr-warden state=restarted enabled=yes
- pause: seconds="{{ warden_restart_wait_time }}"
  when: ansible_check_mode is undefined or not ansible_check_mode
#- name: Check if MapR Fileserver is running
#  shell: "/opt/mapr/initscripts/mapr-mfs status"
#  register: mfs_status
#  failed_when: mfs_status.stdout.find('is running') == -1
