---
# Uninstall Spark on YARN
- name: Stop Spark Historyserver
  shell: maprcli node services -name spark-historyserver -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-spark-historyserver
  package: name=mapr-spark-historyserver state=absent
